public enum Menus {
    SIGN_UP, PROFILE, SHOP, ADMIN, HISTORY, MODE,
    MULTI_PLAYER_MODE_LOGIN, MULTI_PLAYER_MODE_CHARACTER, MULTI_PLAYER_MODE_GAME,
    SINGLE_PLAYER_MODE_GAME,
    SINGLE_PLAYER_MODE_CHARACTER, MAIN, MY_CLAN, JOIN_CLAN, CREATE_CLAN, SECURITY_QUESTION;
}
